"""Self-extracting-payload stub for Vitriol .exe targets.

Distinct from `vitriol_stub.py` (which launches Vitriol.exe itself).
This stub becomes the basis for every Stone-mode .exe Vitriol generates:

  Layout of a Stone .exe at conversion time:
      [stub.exe binary bytes]
      [magic marker: TMUTSTUB-PAYLOAD\\x00]
      [Python source bytes — the same .py runtime we'd otherwise generate]

  At run time:
    1. The stub locates its own .exe path via sys.executable.
    2. Reads the .exe bytes from disk.
    3. Finds the magic marker; everything after is the appended payload.
    4. Decodes payload as UTF-8 Python source.
    5. exec's that source with `__file__` set to the .exe path so the
       payload's self-hash check, self-delete, and counter logic all
       behave exactly as they would in a Stone-mode .py.

  The payload Python source is generated by `_py_embed_to_file_*`
  helpers in `app/format_handlers/masquerade.py`, with hash and IV
  computations that include the stub.exe bytes as a prefix so the
  self-hash check at runtime sees a stable expected hash.
"""
from __future__ import annotations
import os
import sys

# Magic marker that separates the stub binary from the appended payload
# inside a Stone .exe file. Chosen to be ASCII-printable + uncommon so
# .rfind() locates exactly one occurrence (the boundary). Trailing NUL
# disambiguates against the literal string appearing in the stub's own
# code (which is read as bytes from disk including this very constant).
_PAYLOAD_MAGIC = b"TMUTSTUB-PAYLOAD\x00"


def _exe_path() -> str:
    """Path to the running .exe (when frozen) or this script (during dev)."""
    if getattr(sys, "frozen", False):
        return sys.executable
    return os.path.abspath(__file__)


def main() -> int:
    # Immediate visible feedback the moment the bundled Python starts.
    # Appears before reading our own .exe bytes, before exec'ing the
    # appended payload — gives the user something to see during the
    # PyInstaller bootstrap → cryptography import gap (~5-10s).
    print("Loading...", flush=True)

    exe_path = _exe_path()
    try:
        with open(exe_path, "rb") as f:
            data = f.read()
    except OSError as exc:
        print(f"Stub error: cannot read self ({exc}).")
        return 1

    idx = data.rfind(_PAYLOAD_MAGIC)
    if idx < 0:
        print("Stub error: no payload found in this .exe.")
        return 1

    payload = data[idx + len(_PAYLOAD_MAGIC):]
    if not payload:
        print("Stub error: payload is empty.")
        return 1

    try:
        src = payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        print(f"Stub error: payload decode failed ({exc}).")
        return 1

    g = {"__name__": "__main__", "__file__": exe_path}
    try:
        exec(compile(src, "<payload>", "exec"), g)
    except SystemExit:
        raise
    except Exception as exc:
        # Don't leak details of the payload's internals on failure.
        print(f"Rebuild failed.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
